# Site settings
title: Nathan's Blog
email: nathan.daniel.robinson@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my personal blog about my interests, views and experiences.  This is also the
  Blog for my grade 10 personal project.
twitter_box: >
  <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/nrobinson2000" data-widget-id="656147837043015680">Tweets by @nrobinson2000</a>
  <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nrobinson2000
github_username:  nrobinson2000
particle_username: nrobinson2000

nav_message: >

  <h3>About my Blog:</h3>
  <ul>
  <li>This blog is hosted on GitHub pages on my GitHub account.  You can see the <a href="https://github.com/nrobinson2000/nrobinson2000.github.io">source code here.</a></li>
  <br>
  <li>This blog is powered by <a href="https://jekyllrb.com">Jekyll</a>.  Jekyll is an automatic blog / website generator that compiles GitHub flavored markdown into HTML
  files.</li>
  <ul>





# Build settings
kramdown:
  input: GFM
